[world]
name = "Rock Paper Scissors"
seed = "rps-dev"

[namespace]
default = "RPS"

[env]
chain_id = "KATANA_LOCAL"
rpc_url = "http://localhost:5050/"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"

[writers]
"RPS" = ["RPS-game_system"]

[init_call_args]
"RPS-game_system" = []
