[world]
name = "Rock Paper Scissors"
seed = "rps-sepolia"

[namespace]
default = "RPS"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245"
private_key = "0x06c3f4d5e62d4b873a1389cec6671a9ef3414af6321d893bdf3967bc9c77fa47"

[writers]
"RPS" = ["RPS-game_system"]

[init_call_args]
"RPS-game_system" = []
